
[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[font]
normal = { family="MesloLGM Nerd Font" }
offset = { x = 1, y = 0 }
size = 14

[window]
option_as_alt = "Both"

[general]
import = [
  "~/.config/alacritty/hardhacker.toml"
]

